"use strict";

/**
 * Guild bank handouts: the confirmed requests from the EventHelper go into the
 * game, what is ticked off there comes back.
 *
 *   GET  /api/ingest/guildbank/handouts  ->  GuildBankData.lua in every
 *        installed addon folder (same way as CouncilData.lua, lib/council.js);
 *        in game after the next /reload (/ehs bank).
 *   POST /api/ingest/guildbank/handouts  <-  EventHelperSyncDB.guildBankDone,
 *        the entries ticked in game ({ id, via, by, at }), once WoW has
 *        written the SavedVariables.
 *
 * The format `eventhelper-guildbank-handouts` version 1 is shared with the
 * server (repo d:/programming/eventhelper, docs/loot-import.md, "Ausgabeliste
 * für das Addon"). A higher version is refused instead of half written, like
 * the council data.
 *
 * Reporting is idempotent on the server: every id that comes back in any list
 * (ok, duplicate, notConfirmed, unknown) is done for good. Only a failed call
 * (network, 5xx, ...) is worth sending again. The tool remembers the reported
 * ids (config.guildBankDoneReported) so a file that still lists them is not
 * sent again; the addon drops them from guildBankDone once the next
 * GuildBankData.lua no longer lists them.
 */
const fs = require("fs");
const { parseSavedVariables } = require("./luaParser");
const { getJson, postJson, UploadError, SYNC_VERSION } = require("./uploader");
const { toLua, writeToAddonDirs } = require("./council");

const HANDOUTS_FORMAT = "eventhelper-guildbank-handouts";
const HANDOUTS_VERSION = 1;
const HANDOUTS_FILE = "GuildBankData.lua";
// The global the addon reads (GuildBankHandouts.lua).
const HANDOUTS_GLOBAL = "EventHelperSync_GuildBankHandouts";
const HANDOUTS_PATH = "/api/ingest/guildbank/handouts";
// The server takes at most this many entries per report (MAX_DONE).
const MAX_DONE = 200;
// How long a reported id is remembered. By then the addon has long dropped it.
const REPORTED_KEEP_MS = 30 * 24 * 60 * 60 * 1000;
const VIA = new Set(["manual", "mail"]);

class HandoutsError extends Error {
    constructor(message, { status, reported } = {}) {
        super(message);
        this.name = "HandoutsError";
        this.status = status;
        /** Ids of the batches that went through before this error. */
        this.reported = reported || [];
    }
}

// ---------------------------------------------------------------------------
// Server -> game
// ---------------------------------------------------------------------------

/**
 * Check that the server sends what the addon understands.
 * @returns {object} the payload itself
 */
function validateHandouts(payload) {
    if (!payload || typeof payload !== "object" || Array.isArray(payload)) {
        throw new HandoutsError("Der Server hat keine Ausgabeliste geliefert.");
    }
    if (payload.format !== HANDOUTS_FORMAT) {
        throw new HandoutsError(`Unerwartetes Format "${payload.format}" statt "${HANDOUTS_FORMAT}".`);
    }
    const version = payload.version;
    if (typeof version !== "number" || !Number.isInteger(version) || version < 1) {
        throw new HandoutsError(`Ungültige Version der Ausgabeliste: ${JSON.stringify(version)}.`);
    }
    if (version > HANDOUTS_VERSION) {
        throw new HandoutsError(
            `Die Ausgabeliste hat Version ${version}, dieses Sync-Tool kennt nur Version ${HANDOUTS_VERSION}. `
            + "Bitte EventHelper Sync aktualisieren.",
        );
    }
    if (!Array.isArray(payload.banks)) {
        throw new HandoutsError("Die Ausgabeliste enthält keine Gildenbanken.");
    }
    return payload;
}

/** Number of handouts over all banks. */
function countHandouts(payload) {
    const banks = payload && Array.isArray(payload.banks) ? payload.banks : [];
    return banks.reduce((sum, bank) => sum + (bank && Array.isArray(bank.handouts) ? bank.handouts.length : 0), 0);
}

/** The payload from the server (not yet checked). */
async function fetchHandouts(config, { bank = "" } = {}) {
    const query = bank ? `?bank=${encodeURIComponent(String(bank))}` : "";
    try {
        return await getJson(config, `${HANDOUTS_PATH}${query}`);
    } catch (e) {
        // An EventHelper without this route answers 404: not a connection
        // problem, a server that is too old.
        if (e instanceof UploadError && e.status === 404) {
            throw new HandoutsError(
                "Der Server kennt noch keine Ausgabeliste (HTTP 404) — ist der EventHelper aktuell?",
                { status: 404 },
            );
        }
        throw e;
    }
}

/** The whole content of GuildBankData.lua. */
function buildHandoutsFile(payload, { syncVersion = SYNC_VERSION, now = new Date() } = {}) {
    return `-- Generated by EventHelper Sync ${syncVersion} at ${now.toISOString()}. Do not edit; it is overwritten.\n`
        + `${HANDOUTS_GLOBAL} = ${toLua(payload)}\n`;
}

/**
 * Fetch, check and write into every installed addon folder.
 * @param {object} config  as from lib/config.js
 * @param {{ now?: Date, roots?: string[] }} [options]  roots for tests only
 * @returns {Promise<{ payload: object, banks: number, handouts: number, dirs: object[], files: string[], errors: string[] }>}
 */
async function syncHandouts(config, { now = new Date(), roots } = {}) {
    const payload = validateHandouts(await fetchHandouts(config));
    const text = buildHandoutsFile(payload, { now });
    const { dirs, files, errors } = writeToAddonDirs(config, HANDOUTS_FILE, text, { roots });
    return { payload, banks: payload.banks.length, handouts: countHandouts(payload), dirs, files, errors };
}

// ---------------------------------------------------------------------------
// Game -> server
// ---------------------------------------------------------------------------

/**
 * The ticked entries as a clean list, whether the addon wrote a map
 * ({ [id] = { ... } }) or a list. Entries without an id are dropped, an id
 * counts once.
 * @returns {{ id: string, via: string, by: string, at: number }[]}
 */
function normalizeDone(raw) {
    if (!raw || typeof raw !== "object") return [];
    const values = Array.isArray(raw) ? raw : Object.keys(raw).map((key) => {
        const value = raw[key];
        // { [id] = true } is accepted too
        if (value === true) return { id: key };
        if (value && typeof value === "object" && value.id === undefined) return { ...value, id: key };
        return value;
    });
    const out = [];
    const seen = new Set();
    for (const value of values) {
        const entry = typeof value === "string" ? { id: value } : value;
        if (!entry || typeof entry !== "object") continue;
        const id = typeof entry.id === "number" ? String(entry.id) : entry.id;
        if (typeof id !== "string" || !id.trim() || seen.has(id.trim())) continue;
        seen.add(id.trim());
        const at = Number(entry.at);
        out.push({
            id: id.trim(),
            via: VIA.has(entry.via) ? entry.via : "manual",
            by: typeof entry.by === "string" ? entry.by.trim().slice(0, 60) : "",
            at: Number.isFinite(at) && at > 0 ? Math.floor(at) : 0,
        });
    }
    return out;
}

/** EventHelperSyncDB.guildBankDone from a SavedVariables file ([] if none). */
function readGuildBankDone(file) {
    const text = fs.readFileSync(file, "utf8");
    const db = parseSavedVariables(text).EventHelperSyncDB;
    if (!db || typeof db !== "object") return [];
    return normalizeDone(db.guildBankDone);
}

/** The entries whose id has not been reported yet. */
function unreported(entries, reported) {
    const known = reported && typeof reported === "object" ? reported : {};
    return (entries || []).filter((e) => !Object.prototype.hasOwnProperty.call(known, e.id));
}

/** The reported ids without those older than `keepMs`. */
function pruneReported(reported, nowMs = Date.now(), keepMs = REPORTED_KEEP_MS) {
    const out = {};
    for (const [id, at] of Object.entries(reported || {})) {
        if (Number(at) > nowMs - keepMs) out[id] = Number(at);
    }
    return out;
}

/** One entry as the server takes it: optional fields left out. */
function wireEntry(entry) {
    const out = { id: entry.id, via: entry.via || "manual" };
    if (entry.by) out.by = entry.by;
    if (entry.at) out.at = entry.at;
    return out;
}

/**
 * Report the ticked entries, at most MAX_DONE per call.
 * @returns {Promise<{ reported: string[], ok: string[], duplicate: string[], notConfirmed: string[], unknown: string[], invalid: number }>}
 * @throws {HandoutsError} with `reported` = the ids of the batches that went
 *   through before the failing one, and the HTTP status if there was one
 */
async function reportDone(config, entries) {
    const result = { reported: [], ok: [], duplicate: [], notConfirmed: [], unknown: [], invalid: 0 };
    for (let i = 0; i < entries.length; i += MAX_DONE) {
        const batch = entries.slice(i, i + MAX_DONE);
        let answer;
        try {
            answer = await postJson(config, HANDOUTS_PATH, { done: batch.map(wireEntry) });
        } catch (e) {
            const status = e && e.status;
            const why = status === 404
                ? "der Server kennt die Ausgabeliste noch nicht (HTTP 404)"
                : e.message;
            throw new HandoutsError(why, { status, reported: result.reported.slice() });
        }
        const a = answer && typeof answer === "object" ? answer : {};
        for (const key of ["ok", "duplicate", "notConfirmed", "unknown"]) {
            if (Array.isArray(a[key])) result[key].push(...a[key].map(String));
        }
        result.invalid += Number(a.invalid) || 0;
        // Every id of a successful call is done: the server put it into one of
        // the lists (or counted it as invalid, which no resend would fix).
        result.reported.push(...batch.map((e) => e.id));
    }
    return result;
}

module.exports = {
    syncHandouts, fetchHandouts, validateHandouts, buildHandoutsFile, countHandouts,
    normalizeDone, readGuildBankDone, unreported, pruneReported, reportDone,
    HandoutsError, HANDOUTS_FORMAT, HANDOUTS_VERSION, HANDOUTS_FILE, HANDOUTS_GLOBAL, HANDOUTS_PATH,
    MAX_DONE, REPORTED_KEEP_MS,
};
